
name: backend-ci

on:
    push:
        branches: [master]
        paths:
            - "back/**"
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: back
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2
            
            - name: Check
              run: cargo check
            